当异常发生的时候，如果没有预先设定处理方法，程序就会中断

### 常见的异常

ZeroDivisionError除0运算

FileNotFoundError找不到可读文件

ValueError值错误

TypeError类型错误

IndexError索引错误:下标超出序列边界

NameError:使用未被定义的变量

KeyError:键不存在

### 异常的处理

提高程序的稳定性和可靠性。

1.try_except

如果try内代码块执行顺利，except不被触发。

如果try内代码块发生错误，触发except，执行except内代码块。

只要没有出现预判外的错误，无论try内代码块出不出现预判的错误，后面的程序都会顺利执行。

- 单分支
```python
x = 10
y = 0
try:
    z = x/y
except ZeroDivisionError:
    print('0不可以被除')
0不可以被除


x = 10
y = 0
try:
    z = x/y
except NameError:
    print('变量名不存在')
---------------------------------------------------------------------------
ZeroDivisionError                         Traceback (most recent call last)
<ipython-input-826-e46ab5fb9757> in <module>
      2 y = 0
      3 try:
----> 4     z = x/y
      5 except NameError:
      6     print('0不可以被除')

ZeroDivisionError: division by zero
```
- 多分支
```python
ls = []
#ls[3]
#y=m
d = {'name':'zyxhzsh'}
try:
    d['age']
except NameError:
    print('变量名不存在')
except IndexError:
    print('索引超出界限')
except KeyError:
    print('键不存在')
键不存在
```

- 万能异常

Exception

- 获取异常的

as
```
except Exception as e:
    print(e)
```
```python
ls = []
d = {'name':'zyxhzsh'}
try:
    d['age']
except Exception:
    print('出错了，但不知道错误类型')


ls = []
d = {'name':'zyxhzsh'}
try:
    #d['age']
    y = m
except Exception as e:
    print('出错了，不知道错误类型，但可以获取错误的值为:',e)
出错了，不知知道错误类型，但可以获得错误的值为: name 'm' is not defined
```

### try_except与else搭配


如果try模块顺利执行，则else模块也执行。如过try模块有错误，则else模块不执行。
```python
x = 10
y = 1
try:
    z = x/y
except ZeroDivisionError:
    print('0不可以被除')
else:
    print('如果try模块顺利执行，你会看到这句话；如果有异常，那这句话不会出现')
```

### try_except与finally搭配

无论有没有异常，finally模块都会执行
```python
x = 10
y = 1
try:
    z = x/y
except Exception as e:
    print(e)
finally:
    print('无论有没有异常,finally都会执行')
```